#!/bin/bash

# Print usage info to console
usage() {
  echo "WRONG" 1>&2
  exit 1
}

nosuchfile() {
  echo "$1: No such file" 1>&2
  exit 1
}

unreadable() {
  echo "File $1 is unreadable" 1>&2
  exit 1
}

# Require 1 argument
if [ $# -eq 0 ]; then
  usage
fi

# Check if file is exists
if [ ! -f $1 ]; then
  nosuchfile $1
fi

# Check if file is readable
if [ ! -r $1 ]; then
  unreadable $1
fi

# Counter variable
i=0

while read line; do 
  ((i++))
done < $1

echo $i
exit 0
